# Site settings
title: Gustavo Lizárraga
description: 'Esta es la descripción del sitio web.'
url: 'https://lizarragadev.github.io/'
baseurl: '/lizarraga.dev'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gustavo Lizárraga'
  email: lizarraga.dev@gmail.com
  twitter_username: lizarragadev
  facebook_username: lizarraga.dev
  github_username:  lizarragadev
  linkedin_username:  lizarragadev

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
